name: todo_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Immutable models
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # HTTP & API
  dio: ^5.9.0
  graphql_flutter: ^5.2.1

  # Local storage (cross-platform)
  hive_ce: ^2.6.0
  hive_ce_flutter: ^2.1.0

  # Utils
  fpdart: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # Code generation
  build_runner: ^2.4.13
  freezed: ^2.5.8
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4

  # Testing
  mocktail: ^1.0.4

  # App icons
  flutter_launcher_icons: ^0.14.2

flutter:
  uses-material-design: true

  assets:
    - assets/ic_launcher.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/ic_launcher.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/ic_launcher.png"
  windows:
    generate: true
    image_path: "assets/ic_launcher.png"
